# Generated by Django 2.2.6 on 2019-10-16 10:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('max_students', models.PositiveIntegerField(default=20)),
                ('city', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=80)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('age', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('nationality', models.CharField(max_length=80)),
                ('address', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schoolstudents.School')),
            ],
        ),
    ]
